name: Run toml-test
description: Check your parser or writer with toml-test
inputs:
  command:
    description: >-
      Shell command to run your parser or writer
    required: true
  encoder:
    description: >-
      Enable encoder test mode
    required: false
  run:
    description: >-
      Glob-style filter for tests to include
    required: false
  skip:
    description: >-
      Glob-style filter for tests to exclude
    required: false
  parallel:
    description: >-
      Number of test cases to run in parallel
    required: false
  timeout:
    description: >-
      Timeout for each test case
    required: false

runs:
  using: node20
  main: dist/index.js
branding:
  icon: "file-text"
  color: "orange"
